name: CI

on:

  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout PULL|Clone Code
        uses: actions/checkout@v5

      - name: build container
        run: docker build -t web:1.0 -f /opt/actions-runner/_work/cicd_11-30_batch/cicd_11-30_batch/Dockerfile .
  
  sonar:
    needs: build
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  deploy:
    needs: sonar
    runs-on: self-hosted

    steps:
      - name: Start or create container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^test$'; then
            echo "Container exists, starting it..."
            docker start test
          else
            echo "Container does not exist, creating it..."
            docker run -d \
              -v '/opt/actions-runner/_work/cicd_11-30_batch/cicd_11-30_batch/html:/var/www/html/' \
              --name test \
              -p 80:80 \
              web:1.0
          fi